"""
ICS → TimeSlot parser.

Receives a base64-encoded .ics file (RFC 5545), extracts OPAQUE (busy) events,
and returns the complementary list of *available* TimeSlot objects that the
feature-engineering layer already knows how to consume.

The backend is intentionally unaware of whether the ICS was generated by the
frontend from a manual slot selection or uploaded directly by the user.
"""

from __future__ import annotations

import base64
import logging
from datetime import date, datetime
from typing import Any
from zoneinfo import ZoneInfo, ZoneInfoNotFoundError

from icalendar import Calendar

from app.modules.recommendations.recommendations_schemas import TimeSlot

logger = logging.getLogger(__name__)

_DAYS_ORDER = [
    "monday",
    "tuesday",
    "wednesday",
    "thursday",
    "friday",
    "saturday",
    "sunday",
]

# icalendar BYDAY code → day name
_BYDAY_MAP: dict[str, str] = {
    "MO": "monday",
    "TU": "tuesday",
    "WE": "wednesday",
    "TH": "thursday",
    "FR": "friday",
    "SA": "saturday",
    "SU": "sunday",
}


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def parse_to_available_slots(ics_b64: str, tz_name: str) -> list[TimeSlot]:
    """
    Parse a base64 ICS, extract busy blocks, and return the complement as
    available TimeSlot objects (same structure the old available_slots used).

    Returns an empty list on any parse error so the recommendation pipeline
    still runs (with availability_score=0 for all matches).
    """
    try:
        ics_bytes = base64.b64decode(ics_b64)
        cal: Any = Calendar.from_ical(ics_bytes)
    except Exception:
        logger.warning("Failed to decode/parse ICS content; treating user as always available")
        return []

    try:
        tz = _safe_tz(tz_name)
        busy = _extract_busy_slots(cal, tz)
        return _busy_to_available(busy)
    except Exception:
        logger.exception("Unexpected error while computing available slots from ICS")
        return []


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------


def _safe_tz(tz_name: str) -> ZoneInfo:
    try:
        return ZoneInfo(tz_name)
    except (ZoneInfoNotFoundError, KeyError):
        return ZoneInfo("UTC")


def _to_local_datetime(dt_value: date | datetime, tz: ZoneInfo) -> datetime:
    """Normalise a date/datetime (possibly naive or UTC) to the user's TZ."""
    if isinstance(dt_value, datetime):
        if dt_value.tzinfo is None:
            # Floating time — treat as the user's local timezone
            return dt_value.replace(tzinfo=tz)
        return dt_value.astimezone(tz)
    # Plain date (all-day event) — treat as 00:00 in user's TZ
    return datetime(dt_value.year, dt_value.month, dt_value.day, tzinfo=tz)


def _extract_busy_slots(cal: Any, tz: ZoneInfo) -> list[TimeSlot]:
    """Walk VEVENT components and collect (day_of_week, start_hour, end_hour) busy blocks."""
    slots: list[TimeSlot] = []

    for component in cal.walk():
        if component.name != "VEVENT":
            continue

        # Skip events explicitly marked as free (TRANSPARENT)
        transp = str(component.get("TRANSP", "OPAQUE")).upper()
        if transp == "TRANSPARENT":
            continue

        dtstart_prop = component.get("DTSTART")
        dtend_prop = component.get("DTEND")
        if not dtstart_prop or not dtend_prop:
            continue

        start_local = _to_local_datetime(dtstart_prop.dt, tz)
        end_local = _to_local_datetime(dtend_prop.dt, tz)

        start_hour = start_local.hour

        # A DTEND landing on midnight of the *next* day is encoded as end_hour=24.
        if end_local.date() > start_local.date() and end_local.hour == 0 and end_local.minute == 0:
            end_hour = 24
        else:
            end_hour = end_local.hour

        if start_hour >= end_hour:
            continue

        # Determine which day(s) this event applies to.
        # RRULE with BYDAY can cover multiple days in one event.
        days = _days_from_event(component, start_local)

        for day in days:
            slots.append(TimeSlot(day_of_week=day, start_hour=start_hour, end_hour=end_hour))

    return slots


def _days_from_event(component: Any, start_local: datetime) -> list[str]:
    """Return the list of day names this event covers (accounting for RRULE BYDAY)."""
    rrule = component.get("RRULE")
    if rrule and "BYDAY" in rrule:
        days: list[str] = []
        for byday in rrule["BYDAY"]:
            # byday may be a vWeekday like "SA" or a numbered weekday like "1SA"
            code = str(byday)[-2:].upper()
            if code in _BYDAY_MAP:
                days.append(_BYDAY_MAP[code])
        if days:
            return days

    return [start_local.strftime("%A").lower()]


def _busy_to_available(busy_slots: list[TimeSlot]) -> list[TimeSlot]:
    """Invert a set of weekly busy slots to produce available (free) slots."""
    available: list[TimeSlot] = []

    for day in _DAYS_ORDER:
        busy_intervals = sorted(
            (s.start_hour, s.end_hour) for s in busy_slots if s.day_of_week.lower() == day
        )
        free_intervals = _complement_intervals(busy_intervals, (0, 24))

        for start, end in free_intervals:
            available.append(TimeSlot(day_of_week=day, start_hour=start, end_hour=end))

    return available


def _complement_intervals(
    intervals: list[tuple[int, int]],
    full_range: tuple[int, int],
) -> list[tuple[int, int]]:
    """Return the complement of sorted, non-overlapping intervals within full_range."""
    result: list[tuple[int, int]] = []
    cursor = full_range[0]

    for start, end in intervals:
        if start > cursor:
            result.append((cursor, start))
        cursor = max(cursor, end)

    if cursor < full_range[1]:
        result.append((cursor, full_range[1]))

    return result
