"""initial_models

Revision ID: 4c8fa44f1090
Revises: 
Create Date: 2026-05-21 20:07:48.270973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4c8fa44f1090'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teams',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('fifa_ranking', sa.Integer(), nullable=False),
    sa.Column('confederation', sa.String(length=20), nullable=False),
    sa.Column('rival_team_names', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('key_players', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('star_power', sa.Float(), nullable=False),
    sa.Column('narrative_flags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teams_name'), 'teams', ['name'], unique=True)
    op.create_table('matches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('match_id', sa.String(length=10), nullable=False),
    sa.Column('group', sa.String(length=2), nullable=False),
    sa.Column('team_a_id', sa.UUID(), nullable=False),
    sa.Column('team_b_id', sa.UUID(), nullable=False),
    sa.Column('round_in_group', sa.Integer(), nullable=False),
    sa.Column('utc_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('venue', sa.String(length=100), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('venue_country', sa.String(length=50), nullable=False),
    sa.Column('narrative_score', sa.Float(), nullable=False),
    sa.Column('rivalry_index', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['team_a_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['team_b_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matches_group'), 'matches', ['group'], unique=False)
    op.create_index(op.f('ix_matches_match_id'), 'matches', ['match_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_matches_match_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_group'), table_name='matches')
    op.drop_table('matches')
    op.drop_index(op.f('ix_teams_name'), table_name='teams')
    op.drop_table('teams')
    # ### end Alembic commands ###
